///////////////////////////////////////////////////////////
//  orgSpeciality.cs
//  Implementation of the Class orgSpeciality
//  Generated by Enterprise Architect
//  Created on:      16-May-2012 9:16:08 AM
//  Original author: BPostlethwaite
///////////////////////////////////////////////////////////
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using ServD.Enumerations;

namespace ServD.DataModel
{
	/// <summary>
	/// An organisation may provide services under zero, one or more specialties. An
	/// organisation that is a holding company may have no specialties, while those
	/// sites or services held by the holding company may have various.
	/// Note that it is not intended that orgSpeciality is used as the basis for a
	/// service search.  The specialities pertaining to each service offered are more
	/// likely to be the ones relevant to the consumer.
	/// </summary>
	[DataContract(Namespace = Constants.ServDNamespace)]
	public class Speciality
	{
		/// <summary>
		/// The repository unique reference number identifying this item
		/// (This is assigned by the Repository when the item is added)
		/// </summary>
		[DataMember]
		[StringLength(50)]
		public string SpecialityId { get; set; }

		/// <summary>
		/// What is the Status of this record (Complete, Partial, RequiresModeration, Deleted)
		/// </summary>
		[DataMember]
		public RecordStatusEnum RecordStatus { get; set; }

		/// <summary>
		/// What is the sensitivity of this data and who should
		/// be able to see the record.
		/// (Public, Secure, OwnerOnly)
		/// </summary>
		[DataMember]
		public PrivacyIndicatorEnum RecordPrivacyIndicator { get; set; }

		/// <summary>
		/// From a predefined reference table
		/// </summary>
		[DataMember]
		public string SpecialityCode { get; set; }

		/// <summary>
		/// The first date the Speciality is effective for this organisation
		/// </summary>
		[DataMember]
		public DateTime StartDate { get; set; }

		/// <summary>
		/// The last day on which this Speciality is active for this organisation.
		/// </summary>
		[DataMember]
		public DateTime? EndDate { get; set; }

		/// <summary/>
		public Speciality()
		{
		}

		/// <summary/>
		public Speciality(Speciality theOrganizationSpeciality)
		{

		}
	}
}