///////////////////////////////////////////////////////////
//  CoverageArea.cs
//  Implementation of the Class CoverageArea
//  Generated by Enterprise Architect
//  Created on:      16-May-2012 12:28:15 AM
//  Original author: BPostlethwaite
///////////////////////////////////////////////////////////
using System;
using System.Runtime.Serialization;

namespace ServD.Parameters
{
	/// <summary>
	/// 
	/// </summary>
	[DataContract(Namespace = Constants.ServDNamespace)]
	public class CoverageArea
	{
		/// <summary>
		/// The unique Identifier for this coverage area
		/// (Not a part of the Web Services component)
		/// </summary>
		public String CoverageAreaId {get; set; }

		/// <summary>
		/// 
		/// </summary>
		[DataMember]
		public String Name { get; set; }

		/// <summary/>
		public CoverageArea()
		{
		}

		/// <summary/>
		public CoverageArea(CoverageArea theCoverageArea)
		{
			Name = theCoverageArea.Name;
		}
	}
}