///////////////////////////////////////////////////////////
//  LocationSearchParameters.cs
//  Implementation of the Class LocationSearchParameters
//  Generated by Enterprise Architect
//  Created on:      15-May-2012 12:32:07 PM
//  Original author: BPostlethwaite
///////////////////////////////////////////////////////////
using System;
using System.Runtime.Serialization;

namespace ServD.Parameters
{
	/// <summary>
	/// TODO: Need to base these search options based on the Address datamodel type
	/// </summary>
	[DataContract(Namespace = Constants.ServDNamespace)]
	public class LocationSearchParameters
	{
		/// <summary>
		/// 
		/// </summary>
		[DataMember]
		public Boolean IncludeSurrounding { get; set; }

		/// <summary>
		/// 
		/// </summary>
		[DataMember]
		public String LocalGovernmentArea { get; set; }
		
		/// <summary>
		///
		/// </summary>
		[DataMember]
		public String SuburbOrPostcode { get; set; }

		/// <summary/>
		public LocationSearchParameters()
		{
		}

		/// <summary/>
		public LocationSearchParameters(LocationSearchParameters theLocationSearchParameters)
		{
			IncludeSurrounding = theLocationSearchParameters.IncludeSurrounding;
			LocalGovernmentArea = theLocationSearchParameters.LocalGovernmentArea;
			SuburbOrPostcode = theLocationSearchParameters.SuburbOrPostcode;
		}
	}
}