///////////////////////////////////////////////////////////
//  Provider.cs
//  Created on:      10-August-2012 2:00:00 PM
//  Original Author: BPostlethwaite
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using ServD.Common;

namespace ServD.DataModel
{
	/// <value>REVIEW: MF</value>
	/// <summary>
	/// A Provider is any person that delivers clinical value in the
	/// provision of health services. Anyone who becomes a matter of record on the
	/// Electronic Health Record, or is part of a scheduling requirement (operator of
	/// an expensive piece of testing equipment perhaps) has to be identified as a
	/// Provider within this entity.
	/// </summary>
	/// <remarks>
	/// The Surname and Given Name(s) have been moved to the Provider Name object
	/// </remarks>
	[DataContract(Namespace = Constants.ServDNamespace)]
	public class Provider : ModeratedRecord
	{
		/// <summary>
		/// The Id is just used to provide a central value that permits the extraction
		/// </summary>
		/// <remarks>Not a part of the data contract or the entity framework</remarks>
		[StringLength(50)]
		[IgnoreDataMember]
		public override string InternalId { get { return ProviderId; } set { ProviderId = value; } }

		/// <summary>
		/// The type of record this is
		/// </summary>
		/// <remarks>Not a part of the data contract or the entity framework</remarks>
		[IgnoreDataMember]
		public override RecordTypeEnum RecordType { get { return RecordTypeEnum.Provider; } }

		/// <summary>
		/// The unique reference identifying a Provider. This is the primary key for
		/// the Provider entity.
		/// Generated by the application.
		/// </summary>
		[DataMember]
		[StringLength(50)]
		public string ProviderId { get; set; }

		/// <summary>
		/// The Gender (sex) of the Provider.
		/// </summary>
		/// <remarks>
		/// The contents of the attribute are determined from the Sex reference table
		/// renamed from sex_code to comply with HCSP
		/// </remarks>
		/// <cts2code scope='ServD.GEN'>ServD.CTS2.References</cts2code>
		[DataMember]
		[StringLength(64)]
		public string GenderCode { get; set; }

		/// <summary>
		/// The Cultural Ethnicity code provides a link to the Cultural Ethnicity reference
		/// entity to enable the selection of one Cultural Ethnicity type.
		/// It is the self-identified cultural allegiance or background or ethnicity of the Provider.
		/// </summary>
		/// <cts2code scope='ServD.ETH'>ServD.CTS2.References</cts2code>
		[DataMember]
		[StringLength(64)]
		public string CulturalEthnicityCode { get; set; }

		/// <summary>
		/// If there is an image associated with this Provider, its URI can be included here.<br/>
		/// </summary>
		/// <example>A URL for the providers photo could be inserted here</example>
		[DataMember]
		public String ImageURI { get; set; }


		/// <summary>
		/// The public part of the ‘keys’ allocated to an Organization by an accredited
		/// body to support secure exchange of data over the internet.
		/// To be provided by the agency, where available.<br/>
		/// The length of this string is undefined and should be of an un-restricted type.
		/// </summary>
		/// <remarks>This is a base64 encoded digital certificate. The ServD Federation's Profile will
		/// specify the type of certificate to be used and its purpose.</remarks>
		[DataMember]
		public string PublicKey { get; set; }

		/// <summary>
		/// Brief description of any special professional interests a Provider may wish
		/// to list.
		/// </summary>
		[DataMember]
		[StringLength(2048)]
		public string SpecialInterest { get; set; }

		/// <summary>
		/// Brief description of what is offered by a Provider, as a link to further
		/// information.
		/// </summary>
		[DataMember]
		[StringLength(2048)]
		public string Comment { get; set; }

		/// <summary>
		/// The Id of the Primary Site that this Provider works at.
		/// </summary>
		[DataMember]
		[StringLength(50)]
		public String PrimarySiteId { get; set; }

		/// <summary>
		/// The status of this Provider<br/>
		/// </summary>
		/// <example>Unapproved, Active, Suspended, Deregistered</example>
		/// <cts2code scope='ServD.PROVST'>ServD.CTS2.References</cts2code>
		[DataMember]
		[StringLength(64)]
		public string Status { get; set; }

		/// <summary>
		/// Collection of Identifiers associated with this Provider
		/// </summary>
		[DataMember]
		public Identifier[] Identifiers { get; set; }

		/// <summary>
		/// The Preferred Name of the Provider
		/// </summary>
		[DataMember]
		[Required]
		public ProviderName PreferredName { get; set; }

		/// <summary>
		/// Collection of Other names the Provider is known as
		/// </summary>
		[DataMember]
		public ProviderName[] OtherNames { get; set; }

		/// <summary>
		/// Collection of addresses of this Provider
		/// </summary>
		[DataMember]
		public Address[] Addresses { get; set; }

		/// <summary>
		/// Collection of attributes for the Provider
		/// </summary>
		/// <cts2code scope='ServD.ATTT.Prov'>ServD.CTS2.References</cts2code>
		[DataMember]
		public Attribute[] Attributes { get; set; }

		/// <summary>
		/// Collection of credentials (attributes) for the Provider
		/// </summary>
		/// <cts2code scope='ServD.ATTT.Prov.Cred'>ServD.CTS2.References</cts2code>
		[DataMember]
		public Attribute[] Credentials { get; set; }

		/// <summary>
		/// Collection of Qualifications (attributes) for the Provider
		/// </summary>
		/// <cts2code scope='ServD.ATTT.Prov.Qual'>ServD.CTS2.References</cts2code>
		[DataMember]
		public Attribute[] Qualifications { get; set; }

		/// <summary>
		/// Collection of Qualifications (attributes) for the Provider
		/// A Provider may be regulated by one or more external bodies, and only
		/// able to practice at the discretion of those bodies. This entity holds the
		/// particular status of the Provider within the various bodies under which
		/// they are controlled.
		/// </summary>
		/// <cts2code scope='ServD.ATTT.Prov.Reg'>ServD.CTS2.References</cts2code>
		[DataMember]
		public Attribute[] LicenseOrRegistration { get; set; }

		/// <summary>
		/// Collection of Contact points for this Provider
		/// </summary>
		[DataMember]
		public ContactPoint[] ContactPoints { get; set; }

		/// <summary>
		/// Collection of Service Site Ids this Provider works at
		/// </summary>
		[DataMember]
		public ServiceSiteProvider[] ServiceSites { get; set; }

		/// <summary>
		/// Collection of Referral Methods for the Provider
		/// </summary>
		[DataMember]
		public ReferralMethod[] ReferralMethods { get; set; }

		/// <summary>
		/// Collection of Languages spoken/understood by the Provider
		/// </summary>
		[DataMember]
		public ProviderLanguage[] Languages { get; set; }
	}
}